from debian:unstable

RUN apt-get update && \
       apt-get install -y \
       libssl1.1 \
       ca-certificates \
       --no-install-recommends

VOLUME ["/schani_uploader"]

EXPOSE 8000

ENTRYPOINT ["/schani_uploader/webservice"]
